<?php
/**
 * Botgento
 *
 * @category    Botgento
 * @package     Botgento_Base
 * @author      Botgento Team <support@botgento.com>
 * @copyright   Botgento (https://www.botgento.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var Botgento_Base_Helper_Data $botHelper
 */
$botHelper = Mage::helper('botgento');
$messengerappId = $botHelper->getMessengerappId();
$fbPageId = $botHelper->getFbPageId();

if ($botHelper->isEnable() && $botHelper->isFacebookCheckboxEnable()
    && $botHelper->checkCustomerNotExist()
) {
    $randVal = rand(100000, 999999);

    $checkoutSession = Mage::getModel('checkout/session')->getQuote();

    $pageArr = [
        'page_uri' => $botHelper->getCurrentUri(),
        'quote_id' => $checkoutSession->getEntityId()
    ];
    $userRef = $botHelper->generateUserRef($pageArr);
    ?>
    <h2 class="messenger-title" id="messenger-title">
        <?php echo $this->escapeHtml($this->__('Send order updates on:')); ?>
    </h2>
    <div id="fb-loader" class="fb-loader">
        <img src="<?php echo $this->getSkinUrl("images/fb-loader.gif"); ?>"
             alt="<?php echo $this->escapeHtml($this->__('Please wait...')); ?>"
             title="<?php echo $this->escapeHtml($this->__('Please wait...')); ?>"
             class="v-middle"> <?php echo $this->escapeHtml($this->__('Please wait...')); ?>
    </div>
    <input type="hidden" name="fbmessenger" id="fbmessenger" value="" />
    <input type="hidden" name="user_ref" id="user_ref" value="<?php echo $userRef;?>" />
    <div class="fb-messenger-checkbox"
         origin="<?php echo $botHelper->origin(); ?>"
         page_id="<?php echo $this->escapeHtml($fbPageId); ?>"
         messenger_app_id="<?php echo $this->escapeHtml($messengerappId); ?>"
         user_ref="<?php echo $userRef;?>"
         data-ref="BGC_ORDER-UPDATE"
         prechecked="true"
         allow_login="true" size="small">
    </div>
    <script type="text/javascript">
        isCustomerExist = false;
    </script>
<?php } ?>
<?php if ($botHelper->isEnable() && $botHelper->isFacebookCheckboxEnable()
    && !$botHelper->checkCustomerNotExist()
) { ?>
    <input type="hidden" name="fbmessenger" id="fbmessenger" value="checked" />
    <input type="hidden" name="optin" id="optin" value="1"/>
    <script type="text/javascript">
        isCustomerExist = true;
    </script>
<?php } ?>
<script type="text/javascript">
    /**
     * By.: Botgento Inc.
     * Dt.: 30.01.2019
     */
    var isCustomerNotExist = '<?php echo $botHelper->checkCustomerNotExist(); ?>';
    
    if(isCustomerNotExist){
        bgcClass.loadFbCheckboxLib();
        //bindFbAsyncMethods();
    }

    // Add our field to the data submitted by Review.save()
    Review.prototype.save = Review.prototype.save.wrap(function(fbmessenger) {
        if(isCustomerNotExist){
            bgcClass.bgcUserCheckboxConfirm('BGC_ORDER-UPDATE', '<?php echo $userRef; ?>');
        }
        var form = $(this.agreementsForm) ? $(this.agreementsForm) : $(payment.form);
        if (form) {
            var fbField = $('fbmessenger');
            var userRef = $('user_ref');
            form.insert(fbField);
            form.insert(userRef);
        }
        fbmessenger();
    });
</script>
