<?php
/**
 * Botgento
 *
 * @category    Botgento
 * @package     Botgento_Base
 * @author      Botgento Team <support@botgento.com>
 * @copyright   Botgento (https://www.botgento.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var  $botHelper Botgento_Base_Helper_Data
 */
$botHelper = Mage::helper('botgento');
if ($botHelper->isEnable()) {
    $bgcSdkUrl = $botHelper->getBgcSdkUrl(); ?>
    <script type="text/javascript" src="<?php echo $bgcSdkUrl; ?>" async="async"></script>
    <?php
    $curentPageTitle = $this->getLayout()->getBlock('head')->getTitle();
    
    $output = $botHelper->genBGCValue($curentPageTitle);
    $uuid = $botHelper->getUuid();
    $bgc_csrf = $botHelper->getWebsiteApiKeyByCurrentWebsite();

    ?>
    <script type="text/javascript">
        var bgc_uuid = "<?php echo $uuid ?>";
        var bgc = "<?php echo $output ?>";
        var bgc_csrf = "<?php echo $bgc_csrf ?>";

        function setBgc() {
            <?php /*
            due to stop abandon cart for the widget send to messenger button
            modified on: Dec 24, 2018
            jQuery.ajax({
                url: "<?php echo $this->getUrl('botgento/demo/bgc');?>",
                headers : { 'Authorization' : "<?php echo $botHelper->getWebsiteApiKey();?>" },
                success: function (xhr) {
                    console.log(xhr);
                }
            }); */ ?>
        }
    </script>
<?php
}
?>
