<?php
$botHelper = Mage::helper('botgento');
if ($botHelper->isEnable() && $botHelper->getInStockEnable()) {
    $product = $this->getProduct();

    $curentPageTitle = $this->getLayout()->getBlock('head')->getTitle();

    $output = $botHelper->genBGCValue($curentPageTitle);

    if (!empty($product) && !$product->isAvailable()) {

        ?>
        <div class="botgento-instock-alert">
            <p class="botgento-instock-alert-text"><?php echo $this->__('Notify me when this product is back in stock') ?></p>
            <div id="fb-loader" class="fb-loader" style="clear: both">
                <img src="<?php echo $this->getSkinUrl("images/fb-loader.gif"); ?>"
                     alt="<?php echo $this->escapeHtml($this->__('Please wait...')); ?>"
                     title="<?php echo $this->escapeHtml($this->__('Please wait...')); ?>"
                     class="v-middle" width="30px">
            </div>
            <div class="fb-send-to-messenger text-center"
                 messenger_app_id="<?php echo $botHelper->getMessengerappId() ?>"
                 page_id="<?php echo $botHelper->getFbPageId() ?>"
                 data-ref="INSTOCK_<?php echo $output ?>"
                 color="<?php echo $botHelper->getInStockButtonColor() ?>"
                 cta_text="<?php echo $botHelper->getInStockButtonText() ?>"
                 size="<?php echo $botHelper->getInStockButtonSize() ?>">
            </div>
        </div>
        <script type="text/javascript">
            window.isBgcStockAlert = 1;
            window.rememberMStockAlert = function () {
                console.log("Remember Stock Alert Called");
                jQuery.ajax({
                    url: "<?php echo $this->getUrl('botgento/instock/alert');?>",
                    data: {
                        product_id: "<?php echo $product->getId() ?>",
                        uuid: "<?php echo $botHelper->getUuid() ?>"
                    },
                    success: function (xhr) {
                        //console.log(xhr);
                    }
                });
            }
        </script>
<?php
    }
}
?>
